## Put comments here that give an overall description of what your
## functions do

## generats a matrix option that stores the original matrix and can store the inverse matrix

makeCacheMatrix <- function(x = matrix()) {
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) s <<- solve
  getsolve <- function() s
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}


## Takes the matrix generated by makeCacheMatrix and returns the inverse matrix

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  s <- x$getsolve()
  if(!is.null(s)){
    message("Getting cached inverse matrix")
    return(s)
  }
  data <- x$get()  
  matrixsolved <- solve(data,...)
  x$setsolve(matrixsolved)
  matrixsolved
}
